/* ============================================================
   FOCUSFLOW V11 — SaaS PRODUCT EDITION
      Backend-Ready | Auth-Ready | Premium-Ready | Cloud-Ready
         ============================================================ */

         'use strict';

         /* ============================================================
            GLOBAL APP STATE (Production Structure)
               ============================================================ */

               const App = {
                 version: "11.0.0",
                   mode: "local", // change to 'cloud' later
                     isPremium: false,
                       currentUser: null,
                         state: null
                         };

                         /* ============================================================
                            DEFAULT DATA MODEL
                               ============================================================ */

                               const DEFAULT_DATA = {
                                 user: {
                                     id: null,
                                         identity: "",
                                             struggle: "",
                                                 mission: "",
                                                     createdAt: null
                                                       },
                                                         stats: {
                                                             xp: 0,
                                                                 streak: 0,
                                                                     sessions: 0,
                                                                         totalMinutes: 0,
                                                                             lastActiveDate: null,
                                                                                 weeklyFocus: Array(7).fill(0),
                                                                                     moodHistory: []
                                                                                       },
                                                                                         sessions: [],
                                                                                           achievements: {},
                                                                                             leaderboard: []
                                                                                             };

                                                                                             /* ============================================================
                                                                                                AUTH ENGINE (Local + Cloud Ready)
                                                                                                   ============================================================ */

                                                                                                   const AuthEngine = {
                                                                                                     login(name) {
                                                                                                         App.currentUser = {
                                                                                                               id: "user_" + Date.now(),
                                                                                                                     name
                                                                                                                         };
                                                                                                                             if (!App.state) {
                                                                                                                                   App.state = structuredClone(DEFAULT_DATA);
                                                                                                                                         App.state.user.id = App.currentUser.id;
                                                                                                                                               App.state.user.createdAt = new Date().toISOString();
                                                                                                                                                   }
                                                                                                                                                       saveState();
                                                                                                                                                         }
                                                                                                                                                         };

                                                                                                                                                         /* ============================================================
                                                                                                                                                            STORAGE LAYER
                                                                                                                                                               ============================================================ */

                                                                                                                                                               function saveState() {
                                                                                                                                                                 localStorage.setItem("ff_v11", JSON.stringify(App.state));
                                                                                                                                                                 }

                                                                                                                                                                 function loadState() {
                                                                                                                                                                   const saved = localStorage.getItem("ff_v11");
                                                                                                                                                                     App.state = saved ? JSON.parse(saved) : structuredClone(DEFAULT_DATA);
                                                                                                                                                                     }

                                                                                                                                                                     /* ============================================================
                                                                                                                                                                        PREMIUM ENGINE
                                                                                                                                                                           ============================================================ */

                                                                                                                                                                           const PremiumEngine = {
                                                                                                                                                                             unlock() {
                                                                                                                                                                                 App.isPremium = true;
                                                                                                                                                                                     alert("💎 Premium Activated");
                                                                                                                                                                                       },
                                                                                                                                                                                         require(feature) {
                                                                                                                                                                                             if (!App.isPremium) {
                                                                                                                                                                                                   alert("This is a Premium Feature.");
                                                                                                                                                                                                         return false;
                                                                                                                                                                                                             }
                                                                                                                                                                                                                 return true;
                                                                                                                                                                                                                   }
                                                                                                                                                                                                                   };

                                                                                                                                                                                                                   /* ============================================================
                                                                                                                                                                                                                      AI TASK ENGINE
                                                                                                                                                                                                                         ============================================================ */

                                                                                                                                                                                                                         const AIEngine = {
                                                                                                                                                                                                                           suggestTask() {
                                                                                                                                                                                                                               const moodAvg = getMoodAverage();
                                                                                                                                                                                                                                   if (moodAvg > 7) return "🚀 Deep strategic work block";
                                                                                                                                                                                                                                       if (moodAvg > 5) return "📚 Moderate focus session";
                                                                                                                                                                                                                                           return "🔄 Light review & recovery";
                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                             };

                                                                                                                                                                                                                                             function getMoodAverage() {
                                                                                                                                                                                                                                               const arr = App.state.stats.moodHistory.slice(-5);
                                                                                                                                                                                                                                                 if (!arr.length) return 5;
                                                                                                                                                                                                                                                   return arr.reduce((a,b)=>a+b,0)/arr.length;
                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                   /* ============================================================
                                                                                                                                                                                                                                                      SESSION ENGINE
                                                                                                                                                                                                                                                         ============================================================ */

                                                                                                                                                                                                                                                         function completeSession(minutes, type, task) {
                                                                                                                                                                                                                                                           updateStreak();

                                                                                                                                                                                                                                                             const xp = Math.round(minutes * 2 * (1 + App.state.stats.streak * 0.02));
                                                                                                                                                                                                                                                               App.state.stats.xp += xp;
                                                                                                                                                                                                                                                                 App.state.stats.sessions++;
                                                                                                                                                                                                                                                                   App.state.stats.totalMinutes += minutes;

                                                                                                                                                                                                                                                                     App.state.sessions.push({
                                                                                                                                                                                                                                                                         id: Date.now(),
                                                                                                                                                                                                                                                                             type,
                                                                                                                                                                                                                                                                                 minutes,
                                                                                                                                                                                                                                                                                     task,
                                                                                                                                                                                                                                                                                         date: new Date().toISOString()
                                                                                                                                                                                                                                                                                           });

                                                                                                                                                                                                                                                                                             updateWeekly(minutes);
                                                                                                                                                                                                                                                                                               checkAchievements();
                                                                                                                                                                                                                                                                                                 updateLeaderboard();
                                                                                                                                                                                                                                                                                                   saveState();
                                                                                                                                                                                                                                                                                                     refreshUI();
                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                     /* ============================================================
                                                                                                                                                                                                                                                                                                        STREAK ENGINE
                                                                                                                                                                                                                                                                                                           ============================================================ */

                                                                                                                                                                                                                                                                                                           function updateStreak() {
                                                                                                                                                                                                                                                                                                             const today = new Date().toDateString();
                                                                                                                                                                                                                                                                                                               const last = App.state.stats.lastActiveDate;

                                                                                                                                                                                                                                                                                                                 if (!last) {
                                                                                                                                                                                                                                                                                                                     App.state.stats.streak = 1;
                                                                                                                                                                                                                                                                                                                       } else {
                                                                                                                                                                                                                                                                                                                           const diff = (new Date(today) - new Date(last))/(1000*60*60*24);
                                                                                                                                                                                                                                                                                                                               if (diff === 1) App.state.stats.streak++;
                                                                                                                                                                                                                                                                                                                                   else if (diff > 1) App.state.stats.streak = 1;
                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                       App.state.stats.lastActiveDate = today;
                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                       /* ============================================================
                                                                                                                                                                                                                                                                                                                                          WEEKLY TRACKING
                                                                                                                                                                                                                                                                                                                                             ============================================================ */

                                                                                                                                                                                                                                                                                                                                             function updateWeekly(minutes) {
                                                                                                                                                                                                                                                                                                                                               const day = new Date().getDay();
                                                                                                                                                                                                                                                                                                                                                 App.state.stats.weeklyFocus[day] += minutes/60;
                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                 /* ============================================================
                                                                                                                                                                                                                                                                                                                                                    ACHIEVEMENTS
                                                                                                                                                                                                                                                                                                                                                       ============================================================ */

                                                                                                                                                                                                                                                                                                                                                       function checkAchievements() {
                                                                                                                                                                                                                                                                                                                                                         if (App.state.stats.streak >= 7)
                                                                                                                                                                                                                                                                                                                                                             App.state.achievements.streak7 = true;

                                                                                                                                                                                                                                                                                                                                                               if (App.state.stats.totalMinutes >= 6000)
                                                                                                                                                                                                                                                                                                                                                                   App.state.achievements.hours100 = true;

                                                                                                                                                                                                                                                                                                                                                                     if (App.state.stats.sessions >= 30)
                                                                                                                                                                                                                                                                                                                                                                         App.state.achievements.sessions30 = true;
                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                         /* ============================================================
                                                                                                                                                                                                                                                                                                                                                                            LEADERBOARD (Local Simulation)
                                                                                                                                                                                                                                                                                                                                                                               ============================================================ */

                                                                                                                                                                                                                                                                                                                                                                               function updateLeaderboard() {
                                                                                                                                                                                                                                                                                                                                                                                 App.state.leaderboard = [
                                                                                                                                                                                                                                                                                                                                                                                     {name:"You", xp:App.state.stats.xp},
                                                                                                                                                                                                                                                                                                                                                                                         {name:"Alpha", xp:1200},
                                                                                                                                                                                                                                                                                                                                                                                             {name:"Zenith", xp:950}
                                                                                                                                                                                                                                                                                                                                                                                               ].sort((a,b)=>b.xp-a.xp);
                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                               /* ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                  DISCIPLINE SCORE
                                                                                                                                                                                                                                                                                                                                                                                                     ============================================================ */

                                                                                                                                                                                                                                                                                                                                                                                                     function calculateScore() {
                                                                                                                                                                                                                                                                                                                                                                                                       const consistency = Math.min(App.state.stats.sessions/50,1)*30;
                                                                                                                                                                                                                                                                                                                                                                                                         const streakScore = Math.min(App.state.stats.streak/30,1)*30;
                                                                                                                                                                                                                                                                                                                                                                                                           const hourScore = Math.min(App.state.stats.totalMinutes/6000,1)*40;
                                                                                                                                                                                                                                                                                                                                                                                                             return Math.round(consistency+streakScore+hourScore);
                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                             /* ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                UI REFRESH
                                                                                                                                                                                                                                                                                                                                                                                                                   ============================================================ */

                                                                                                                                                                                                                                                                                                                                                                                                                   function refreshUI() {
                                                                                                                                                                                                                                                                                                                                                                                                                     const xpEl = document.getElementById("hdr-xp");
                                                                                                                                                                                                                                                                                                                                                                                                                       if (xpEl) xpEl.textContent = App.state.stats.xp + " XP";

                                                                                                                                                                                                                                                                                                                                                                                                                         const streakEl = document.getElementById("st-str");
                                                                                                                                                                                                                                                                                                                                                                                                                           if (streakEl) streakEl.textContent = App.state.stats.streak + "🔥";

                                                                                                                                                                                                                                                                                                                                                                                                                             const scoreEl = document.getElementById("sc-n");
                                                                                                                                                                                                                                                                                                                                                                                                                               if (scoreEl) scoreEl.textContent = calculateScore();

                                                                                                                                                                                                                                                                                                                                                                                                                                 renderSessionHistory();
                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                 /* ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                    SESSION HISTORY UI
                                                                                                                                                                                                                                                                                                                                                                                                                                       ============================================================ */

                                                                                                                                                                                                                                                                                                                                                                                                                                       function renderSessionHistory() {
                                                                                                                                                                                                                                                                                                                                                                                                                                         const el = document.getElementById("session-history");
                                                                                                                                                                                                                                                                                                                                                                                                                                           if (!el) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                             el.innerHTML = "";

                                                                                                                                                                                                                                                                                                                                                                                                                                               App.state.sessions.slice(-5).reverse().forEach(s=>{
                                                                                                                                                                                                                                                                                                                                                                                                                                                   const div = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                                                                                                       div.className = "hist-row";
                                                                                                                                                                                                                                                                                                                                                                                                                                                           div.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div>${s.type.toUpperCase()}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div>${s.minutes}m</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               el.appendChild(div);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 /* ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    INIT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ============================================================ */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       document.addEventListener("DOMContentLoaded", ()=>{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         loadState();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           refreshUI();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });